### ISSUE TITLE
build failure on Xcode 7.3.1

### ISSUE THREAD

**Issue by ikzjfr0** [svdo/swift-SelfSignedCert#1]
just wondering what version of Xcode that you used? I come out following build error on Xcode7.3.1

![image](https://cloud.githubusercontent.com/assets/6456056/26616909/60876b5e-4615-11e7-9445-9e4e46756b58.png)

**Comment by svdo** [comment]
Sorry, I don't recall. I just bit the bullet and updated the project (and its dependencies) to Swift 3 (using Xcode 8.3.2). I don't have the bandwidth to support older versions, I hope this helps you...

**Comment by ikzjfr0** [comment]
that's so so cool and it works on Xcode8.3.1 ：） thx
