### ISSUE TITLE
Not support Carthage

### ISSUE THREAD

**Issue by ikzjfr0** [svdo/swift-SelfSignedCert#2]
When Cartage is used instead of Cocoapod, it comes this error when 
```
carthage update
```
it need to have the scheme to be shared

![image](https://cloud.githubusercontent.com/assets/6456056/26662205/ab7708e4-46c5-11e7-8572-bb4207b9daaf.png)

**Comment by ikzjfr0** [comment]
my solution for Carthage here: https://github.com/ikzjfr0/swift-SelfSignedCert/commits/master. A little mess there since i have tried couple times before it works :)

**Comment by svdo** [comment]
I have no experience with Carthage, but wouldn't that require setting up a Cartfile to specify the dependencies of this library?

**Comment by ikzjfr0** [comment]
Two key points to support Carthage if you are creating a framework that can be used in a Carthage managed project
1. set shared scheme, so Carthage knows what to build
2. include third party framework into generated framework

You can refer to this: https://medium.com/@filippotosetto/how-to-create-a-carthage-framework-8d9d65f98ac2

**Comment by svdo** [comment]
I think it should work with Carthage now. I had to update one of the dependent frameworks (SwiftBytes) because it wasn't using the naming convention Carthage expects (name of project/scheme/target was `Bytes` whereas the Cocoapod was named `SwiftBytes`; all are now `SwiftBytes`.)

**Comment by ikzjfr0** [comment]
:) i don't think your new one works well with Cathage since i can get following error:
dyld: Library not loaded: @rpath/SecurityExtensions.framework/SecurityExtensions

Attached is a quick demo :)
[Xbox 2.zip](https://github.com/svdo/swift-SelfSignedCert/files/1046166/Xbox.2.zip)

**Comment by ikzjfr0** [comment]
Thanks so much for your help. it works :)
By the way, all my story is I need to create a sign-signed certificate in iOS. Attached is my  demo spike to generate a self-signed certificate, you saved me a lot of time on it :)

[SSCSpike_Carthage.zip](https://github.com/svdo/swift-SelfSignedCert/files/1046186/SSCSpike_Carthage.zip)
