### ISSUE TITLE
Appstore review

### ISSUE THREAD

**Issue by Tulakshana** [svdo/swift-SelfSignedCert#4]
Hi,

Have you used this in an app in production? My concern is the review Apple conducts for the app submissions?

**Comment by svdo** [comment]
I have not used this in production, just for a demo. App review should not a problem, this doesn't do anything that is prohibited AFAIK. I would be more concerned with the remark I put in the readme:

> Please note that I'm not a security expert. This framework has not been reviewed by a security expert. Until it has, please use with caution! And in any case (reviewed or not), using it is always at your own risk of course.
