### ISSUE TITLE
Find identity with public key

### ISSUE THREAD

**Issue by skogland** [svdo/swift-SelfSignedCert#6]
Hi!

I was wondering if there is a reason for `static func find(withPublicKey pubKey:SecKey) -> SecIdentity?` in `SecIdentity+SelfSigned.swift` not being public? I'd really like get the stored identity+certificate with this method.

**Comment by svdo** [comment]
No particular reason that I can think of anymore, other than maybe being careful about making things public that maybe don't need to be; making things public is easy, but removing things from an API creates problems 😉

I'd be happy to make things that you need public!

**Comment by skogland** [comment]
Alright, I think that would be great! I could play around with my fork for a bit, just to make sure that the change is needed, but it looks like its just what I need.

**Comment by svdo** [comment]
Whichever you like, just let me know :) I can do it this weekend, but of course if more changes are needed I prefer to do them in one go.

**Comment by svdo** [comment]
You know what, I'll just make you a maintainer, that should make things a lot easier.

**Comment by skogland** [comment]
Fantastic! I do have a couple of other thing I'd like to do as well, like SPM support, EC key support and I see the Cartfile needs an update :)

**Comment by svdo** [comment]
Perfect! SPM support is indeed nice. I'm not sure how relevant Carthage support is nowadays, but it doesn't hurt. Go for it :)
