### ISSUE TITLE
SecIdentity not found via `SecIdentity.find(withPublicKey: ...)`

### ISSUE THREAD

**Issue by haemi** [svdo/swift-SelfSignedCert#8]
I tried to create a public/private key pair and then get the `SecIdentity` for it, but it always returns nil:

```
        // generate key pair
        let pair = try! SecKey.generateKeyPair(ofSize: 1024)

        // save public and private key to keychain
        let publicKey = SecKey.create(withData: pair.publicKey.keyData!)
        _ = SecKey.create(withData: pair.privateKey.keyData!)

        // get identity for public key
        let identity = SecIdentity.find(withPublicKey: publicKey!)
        debugPrint(identity)
```

Am I missing something here?

**Comment by svdo** [comment]
It has been many years since I have actually used this myself, so I'm quite hazy on the details. Did you look at the unit tests? Specifically here: https://github.com/svdo/swift-SelfSignedCert/blob/b598d8e4960a25347cce4266457580e5bce66224/SelfSignedCertTests/CertificateRequestTests.swift#L119-L157. I'm hoping that this may give you the much needed clues...

**Comment by haemi** [comment]
thanks, this helped already a LOT! Is it possible that it only works for keys with bitsize >= 2048? I do get nil when calling `SecCertificateCreateWithData(nil, signedData as CFData)` when using bitsize = 1024

**Comment by svdo** [comment]
I'm sorry, I don't know. Maybe that key size is considered insecure nowadays? One thing that I did when debugging this stuff: when running on the simulator, you can find the actual key chain file that is being used by the app and manually see what's in there. That way you can maybe see whether storing or retrieving fails.

**Comment by haemi** [comment]
thanks a lot for your help, I close this as it's not a really issue 🙂

**Comment by svdo** [comment]
My pleasure! If you find out, maybe you can post the solution here for our future selves 😀
