### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by Alkenso** [svdo/swift-SelfSignedCert#9]
Seems this is the one adequate Swift library for certificate generation.
Please add Swift Package Manager support

**Comment by svdo** [comment]
Thanks, happy dat it is useful to you. If you could create a PR that would be great!

**Comment by Alkenso** [comment]
Unfortunately it has dependencies of yours that also does not support SPM.

If you will add it, that will be great

**Comment by svdo** [comment]
Ok I'll see what I can do. It will take some time though, given other priorities that I have at the moment...

**Comment by skogland** [comment]
I have a fork with SPM-support that I didn't get around to submit a PR for. I'll make the PR's and maybe we can get those merged.

**Comment by svdo** [comment]
I just released 3.0.1 with SPM support. HUGE thanks to @skogland for doing so much of the hard work!!

**Comment by skogland** [comment]
Happy to be of help, @svdo  :)
